_target_: clip.models.TextPart

vocab_size: ${vocab_size}
hidden_size: 256
num_hidden_layers: 4
num_attention_heads: 4
intermediate_size: 1024
max_position_embeddings: 256
hidden_act: gelu_new
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
position_embedding_type: relative_key_query