_target_: clip.models.ImagePart

depths: [3, 3, 3, 3]
num_heads: [2, 4, 6, 8]
num_channels: 3
embed_dim: 96
window_size: 7
mlp_ratio: 4
hidden_dropout_prob: 0.2
attention_probs_dropout_prob: 0.2
drop_path_rate: 0.4
hidden_act: gelu
use_absolute_embeddings: false
