defaults:
  - default

_target_: src.models.DistilCLIPModule

img_proj:
  _target_: torch.nn.Linear
  in_features: ${embedding_dim}
  out_features: ${teacher_embedding_dim}
txt_proj:
  _target_: torch.nn.Linear
  in_features: ${embedding_dim}
  out_features: ${teacher_embedding_dim}
teacher:
  _target_: transformers.CLIPModel.from_pretrained
  pretrained_model_name_or_path: ${teacher_pretrained}

l1_coeff: 5.0
cos_coeff: 5.0
