# @package _global_

defaults:
  - _self_
  - data: default
  - model: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

ckpt_path: ???
