# @package _global_

task_name: "debug"

callbacks: null
logger: null

extras:
  ignore_warnings: false
  enforce_tags: false

hydra:
  job_logging:
    root:
      level: DEBUG

trainer:
  accelerator: gpu
  strategy: auto
  max_steps: 100
  devices: 1
  detect_anomaly: true
