# @package _global_

task_name: "debug"

callbacks: null
logger: null

extras:
  ignore_warnings: False
  enforce_tags: False

hydra:
  job_logging:
    root:
      level: DEBUG

trainer:
  max_epochs: 1
  devices: 1
  detect_anomaly: true

data:
  num_workers: 0
  pin_memory: False
